name: Waka Readme

on:
  schedule:
    # Runs at 6PM (EAT)
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check WakaTime API key
        run: |
          if [ -z "$WAKATIME_API_KEY" ]; then
            echo "WakaTime API key is empty!"
            exit 1
          else
            echo "WakaTime API key is set and has length ${#WAKATIME_API_KEY}"
          fi
        shell: bash
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "True"
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_PROFILE_VIEWS: "False"
          BADGE_STYLE: "flat"
          IGNORED_REPOS: "tokio, uring_fast_read, mintlify_docs, docs, multi_head_attention, airbyte, kuard"
